### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by matt-curtis** [OlexiyKhokhlov/PDFium#1]
Hello, thanks for the work making PDFium easier to build. What would it take to update this repo to the latest version of PDFium available?

**Comment by matt-curtis** [comment]
Nevermind - took awhile, but I figured it out.

**Comment by OlexiyKhokhlov** [comment]
Hello,
I have no projects with PDF now. So don't know when I can return to that.
May be in the next month but I'm not sure.
